### ISSUE TITLE
Upgrade to React Scripts to 5.0.0 & React 18

### ISSUE THREAD

**Issue by NickCallaghan** [ClimateMind/climatemind-frontend#306]

**Comment by morelmiles** [comment]
Hi @NickCallaghan, 
Can I be assigned to work on this?

**Comment by morelmiles** [comment]
Hi @Svenstar74 
Is this something that Climate Mind is still interested in? Please let me know so that I do not waste my effort since this issue requires a bit of work?

Cheers.

**Comment by Svenstar74** [comment]
Hello @morelmiles, thank you for your interest in contributing. At the moment we don't want any large changes to the codebase. With the change to React 18 there are probably other dependencies like the material/ui that needs to be upgraded as well. So this issue may be something for the future.

**Comment by morelmiles** [comment]
I agree with you. It'd be a large change. 
Could you then go ahead and assign/mention me in the issues where you need help.
