### ISSUE TITLE
Drawer Component on Conversation Table styling issue on hover

### ISSUE THREAD

**Issue by NickCallaghan** [ClimateMind/climatemind-frontend#307]
Styling of the collapsed drawer component shows incorrectly on mousover. 
NB. This component is in our storybook under `pages/ConversationDashboard`. Use `npm run storybook` to open storybook. 

### Actual
<img width="434" alt="Screenshot 2022-08-01 at 16 25 59" src="https://user-images.githubusercontent.com/44759513/182185115-8e86e36b-ed66-4f85-8a95-a33f8fa48e82.png">

### Expected
<img width="436" alt="Screenshot 2022-08-01 at 16 25 45" src="https://user-images.githubusercontent.com/44759513/182185094-cd5eb5b8-0a04-44bd-9f13-168d5e9bc181.png">

**Comment by brianpeiris** [comment]
Has this issue already been resolved? It's not clear to me exactly what the incorrect styling issue is.

**Comment by NickCallaghan** [comment]
Hi @brianpeiris this issue has not been resolved. The issue is that the drawer is transparent when it should be colored to match the theme.

**Comment by brianpeiris** [comment]
Ah, I see. Thanks for clarifying.
